version: '3.8'

services:
  empsync-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://empsync-2.onrender.com/api
    depends_on:
      - backend
    volumes:
      - .:/app

    restart: unless-stopped
    networks:
      - empsync-network

networks:
  empsync-network:
    external: true
